### ISSUE TITLE
Unsolved error during toolhead.manual_move

### ISSUE THREAD

**Issue by fraserw** [viesturz/NozzleAlign#4]
I am trying to add a new function to extend probe calibration for the BLTouch. 

I have defined a minimal test function called HACK that simply adjusts the z-height based on a previously determined location vector. This returns "!! Internal error..." and I cannot see why:

   def cmd_HACK(self, gcmd):
        toolhead = self.printer.lookup_object('toolhead')
        start_pos = toolhead.get_position()
        location = [99., 218. ,58.]
        self.gcode.respond_info("%.3f %.3f %.3f"%(location[0],location[1],location[2]))

        new_z = location[2] + 10.0
        toolhead.manual_move([None, None, new_z], self.lift_speed)

I am sure I am missing something obvious.

**Comment by viesturz** [comment]
You should be able to see the full error in klippy.log . Start from the
bottom and scroll up until you see a python stack trace printed

**Comment by fraserw** [comment]
Thanks. I wasn't aware of the log. That revealed my issues.

**Comment by fraserw** [comment]
Solved!
